### ISSUE TITLE
请求授权

### ISSUE THREAD

**Issue by drinktoomuchsax** [Tonanguyxiro/EE205_Signal_and_System_LAB#1]
学长/学姐好，请求在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及使用你的仓库：）

**Comment by Tonanguyxiro** [comment]
同意的

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Cao&nbsp;zhengyang ***@***.***&gt;;
发送时间：2023年4月23日(星期天) 凌晨0:31
收件人："Tonanguyxiro/EE205_Signal_and_System_LAB" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[Tonanguyxiro/EE205_Signal_and_System_LAB] 请求授权 (Issue #1)
-----------------------------------

 

 
学长/学姐好，请求在SUSTech-EE-Course-Hero里引用你的项目以及使用你的仓库：）
